DROP TABLE CUSTOMERS PURGE;

CREATE TABLE CUSTOMERS (
    customer_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_name        VARCHAR2(100) NOT NULL,
    age                  NUMBER NOT NULL,
    balance              NUMBER(12, 2) NOT NULL,
    loan_interest_rate   NUMBER(4, 2) DEFAULT 0.00 NOT NULL,
    loan_due_date        DATE,
    is_vip               BOOLEAN DEFAULT FALSE NOT NULL
);

INSERT INTO CUSTOMERS (customer_name, age, balance, loan_interest_rate, loan_due_date, is_vip) VALUES ('Alice Smith', 65, 5000.00, 6.00, SYSDATE + 15, FALSE);
INSERT INTO CUSTOMERS (customer_name, age, balance, loan_interest_rate, loan_due_date, is_vip) VALUES ('Bob Johnson', 40, 12000.00, 7.00, SYSDATE + 45, FALSE);
INSERT INTO CUSTOMERS (customer_name, age, balance, loan_interest_rate, loan_due_date, is_vip) VALUES ('Carol White', 70, 15000.00, 5.00, SYSDATE + 25, FALSE);
INSERT INTO CUSTOMERS (customer_name, age, balance, loan_interest_rate, loan_due_date, is_vip) VALUES ('David Green', 30, 8000.00, 6.50, SYSDATE + 5, FALSE);
INSERT INTO CUSTOMERS (customer_name, age, balance, loan_interest_rate, loan_due_date, is_vip) VALUES ('Eve Black', 55, 2000.00, 7.20, SYSDATE + 60, FALSE);
INSERT INTO CUSTOMERS (customer_name, age, balance, loan_interest_rate, loan_due_date, is_vip) VALUES ('Frank Blue', 62, 11000.00, 6.80, SYSDATE + 10, FALSE);
INSERT INTO CUSTOMERS (customer_name, age, balance, loan_interest_rate, loan_due_date, is_vip) VALUES ('Grace Grey', 35, 9500.00, 7.10, SYSDATE + 75, FALSE);
INSERT INTO CUSTOMERS (customer_name, age, balance, loan_interest_rate, loan_due_date, is_vip) VALUES ('Harry Brown', 80, 7500.00, 6.30, SYSDATE + 20, FALSE);

