
CREATE TABLE ACCOUNTS (
    account_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    account_type         VARCHAR2(50) NOT NULL CHECK (account_type IN ('Savings', 'Checking')),
    balance              NUMBER(12, 2) DEFAULT 0.00 NOT NULL
);

INSERT INTO ACCOUNTS (account_type, balance) VALUES ('Savings', 1500.00);
INSERT INTO ACCOUNTS (account_type, balance) VALUES ('Checking', 2000.00);
INSERT INTO ACCOUNTS (account_type, balance) VALUES ('Savings', 5000.00);
INSERT INTO ACCOUNTS (account_type, balance) VALUES ('Savings', 750.00);
INSERT INTO ACCOUNTS (account_type, balance) VALUES ('Checking', 10000.00);
INSERT INTO ACCOUNTS (account_type, balance) VALUES ('Savings', 300.00);
INSERT INTO ACCOUNTS (account_type, balance) VALUES ('Savings', 2500.00);

select * from accounts;

CREATE TABLE EMPLOYEES (
    employee_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_name        VARCHAR2(100) NOT NULL,
    department_id        NUMBER NOT NULL,
    salary               NUMBER(10, 2) DEFAULT 0.00 NOT NULL,
    performance_score    NUMBER(3)
);

INSERT INTO EMPLOYEES (employee_name, department_id, salary, performance_score) VALUES ('John Doe', 10, 50000.00, 85);
INSERT INTO EMPLOYEES (employee_name, department_id, salary, performance_score) VALUES ('Jane Smith', 20, 60000.00, 92);
INSERT INTO EMPLOYEES (employee_name, department_id, salary, performance_score) VALUES ('Peter Jones', 10, 45000.00, 78);
INSERT INTO EMPLOYEES (employee_name, department_id, salary, performance_score) VALUES ('Mary Brown', 30, 70000.00, 95);
INSERT INTO EMPLOYEES (employee_name, department_id, salary, performance_score) VALUES ('David Lee', 20, 55000.00, 88);
INSERT INTO EMPLOYEES (employee_name, department_id, salary, performance_score) VALUES ('Sarah Davis', 10, 48000.00, 80);

SELECT * from EMPLOYEES;
